### ISSUE TITLE
目前插件最新版本好像已经不兼容halo2.17了

### ISSUE THREAD

**Issue by JeffreyZeng-dev** [Rainsheep/halo-plugin-meilisearch#3]
2024-06-27T10:40:27.842+08:00 ERROR 7 --- [run.halo.app.core.extension.reconciler.PluginReconciler-t-1] r.h.a.e.controller.DefaultController     : Reconciler in run.halo.app.core.extension.reconciler.PluginReconciler-worker-1 aborted with an error, re-enqueuing...

java.lang.NoClassDefFoundError: run.halo.app.search.post.PostSearchService
	at java.base/java.lang.ClassLoader.defineClassImpl(Native Method) ~[na:na]
	at java.base/java.lang.ClassLoader.defineClassInternal(Unknown Source) ~[na:na]
	at java.base/java.lang.ClassLoader.defineClass(Unknown Source) ~[na:na]
	at java.base/java.security.SecureClassLoader.defineClass(Unknown Source) ~[na:na]
	at java.base/java.net.URLClassLoader.defineClass(Unknown Source) ~[na:na]
	at java.base/java.net.URLClassLoader$ClassFinder.run(Unknown Source) ~[na:na]
	at java.base/java.net.URLClassLoader$ClassFinder.run(Unknown Source) ~[na:na]
	at java.base/java.security.AccessController.doPrivileged(Unknown Source) ~[na:na]
	at java.base/java.net.URLClassLoader.findClass(Unknown Source) ~[na:na]
	at org.pf4j.PluginClassLoader.loadClass(PluginClassLoader.java:153) ~[pf4j-3.12.0.jar:3.12.0]
	at run.halo.app.plugin.DefaultPluginApplicationContextFactory.lambda$create$6(DefaultPluginApplicationContextFactory.java:146) ~[classes/:2.17.0-alpha.1]
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[na:na]
	at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(Unknown Source) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[na:na]
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) ~[na:na]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[na:na]
	at run.halo.app.plugin.DefaultPluginApplicationContextFactory.create(DefaultPluginApplicationContextFactory.java:153) ~[classes/:2.17.0-alpha.1]
	at run.halo.app.plugin.SpringPlugin.start(SpringPlugin.java:32) ~[classes/:2.17.0-alpha.1]
	at org.pf4j.AbstractPluginManager.startPlugin(AbstractPluginManager.java:441) ~[pf4j-3.12.0.jar:3.12.0]
	at run.halo.app.core.extension.reconciler.PluginReconciler.enablePlugin(PluginReconciler.java:310) ~[classes/:2.17.0-alpha.1]
	at run.halo.app.core.extension.reconciler.PluginReconciler.lambda$reconcile$5(PluginReconciler.java:147) ~[classes/:2.17.0-alpha.1]
	at run.halo.app.core.extension.reconciler.PluginReconciler.lambda$reconcile$7(PluginReconciler.java:155) ~[classes/:2.17.0-alpha.1]
	at java.base/java.util.Optional.map(Unknown Source) ~[na:na]
	at run.halo.app.core.extension.reconciler.PluginReconciler.reconcile(PluginReconciler.java:110) ~[classes/:2.17.0-alpha.1]
	at run.halo.app.core.extension.reconciler.PluginReconciler.reconcile(PluginReconciler.java:74) ~[classes/:2.17.0-alpha.1]
	at run.halo.app.extension.controller.DefaultController$Worker.run(DefaultController.java:163) ~[api-2.17.0-alpha.1.jar:na]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]
	at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
Caused by: java.lang.ClassNotFoundException: run.halo.app.search.post.PostSearchService
	at org.pf4j.PluginClassLoader.loadClass(PluginClassLoader.java:169) ~[pf4j-3.12.0.jar:3.12.0]
	... 34 common frames omitted

**Comment by Rainsheep** [comment]
yes, 参考 https://github.com/halo-dev/halo/issues/5339#issuecomment-2187839776，
2.17 对搜索功能进行了重构，插件还未兼容。
代码已经开发好了，我见 2.17 还未发布？   发布完成后插件会同步更新

**Comment by JeffreyZeng-dev** [comment]
我用的是[2.17.0-alpha.1](https://github.com/halo-dev/halo/releases/tag/v2.17.0-alpha.1)

**Comment by wxyShine** [comment]
快了 月底前应该会发正式版

**Comment by JohnNiang** [comment]
Hi @Rainsheep，可以先发布新版，并设置一下最低 Halo 版本要求即可。这样可以给尝鲜用户提前试用，提前发现问题。

https://github.com/Rainsheep/halo-plugin-meilisearch/blob/77e9a57ac579c1e69ccdc345f841957318aacd9c/src/main/resources/plugin.yaml#L7

**Comment by Rainsheep** [comment]
下午会更新适配 2.17 的版本

**Comment by Rainsheep** [comment]
在 release 可以下载 v2.0.0-alpha.1 版，适配了 halo v2.17.0-alpha.2，存在 bug，不影响基本功能的使用。

**Comment by JeffreyZeng-dev** [comment]
> 在 release 可以下载 v2.0.0-alpha.1 版，适配了 halo v2.17.0-alpha.2，存在 bug，不影响基本功能的使用。
貌似更新了以后都搜索不出结果了。

**Comment by Rainsheep** [comment]
@UPToZ-Core  刷新下搜索引擎试试。

**Comment by Rainsheep** [comment]
发布了新版 v2.0.0，完全适配 2.17，并修复了已知 bug。  辛苦帮发布到应用市场 @JohnNiang

**Comment by wxyShine** [comment]
> > 在 release 可以下载 v2.0.0-alpha.1 版，适配了 halo v2.17.0-alpha.2，存在 bug，不影响基本功能的使用。
> > 貌似更新了以后都搜索不出结果了。

新版本好像没报错日志 一直搜索不到东西。 Meilisearch2.0.0    Halo [2.17.0-beta.1](https://www.lxware.cn/docs/helpcenter/halo-pro/changlog)

**Comment by JeffreyZeng-dev** [comment]
新版本搜索不到任何结果了

**Comment by Rainsheep** [comment]
@wxyShine @UPToZ-Core  能否协助我进行远程调试，qq/wx 发我邮箱 1045674971@qq.com

**Comment by Rainsheep** [comment]
@UPToZ-Core 搜索不到结果有尝试手动刷新索引吗？

**Comment by mahaonanStart** [comment]
新版貌似搜不到东西呀，meilisearch版本1.9.0，halo2.17，刷新索引也没用，meilisearch里面看不到有index

**Comment by Rainsheep** [comment]
@mahaonanStart 看最新的 readme，在设置中需要选择 meilisearch search engine。
如果问题解决，辛苦反馈下

**Comment by mahaonanStart** [comment]
> @mahaonanStart 看最新的 readme，在设置中需要选择 meilisearch search engine。 如果问题解决，辛苦反馈下

<img width="1145" alt="image" src="https://github.com/Rainsheep/halo-plugin-meilisearch/assets/44892851/164c1560-69f8-493e-a0e3-9799f9a0183d">
设置了，貌似还不行啊

**Comment by JeffreyZeng-dev** [comment]
> > @mahaonanStart 看最新的 readme，在设置中需要选择 meilisearch search engine。 如果问题解决，辛苦反馈下
> 
> <img alt="image" width="1145" src="https://private-user-images.githubusercontent.com/44892851/345867647-164c1560-69f8-493e-a0e3-9799f9a0183d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxMDM3NDUsIm5iZiI6MTcyMDEwMzQ0NSwicGF0aCI6Ii80NDg5Mjg1MS8zNDU4Njc2NDctMTY0YzE1NjAtNjlmOC00OTNlLWEwZTMtOTc5OWY5YTAxODNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA0VDE0MzA0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZkNjRjOGViNDRmYjA0MGFmZjU0MzEyNDgyNjk2ZWUzZmNjYzU2MjhhNTAyNDc5NDhmMzA1Zjk1YzUyNGJiNjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fX7VbB36eLSDANqJdRVjtznYsvjEc6qqI7LF0FodPyU"> 设置了，貌似还不行啊

@mahaonanStart 需要去Meilisearch中删除掉halo的元数据。

**Comment by mahaonanStart** [comment]
> > > @mahaonanStart 看最新的 readme，在设置中需要选择 meilisearch search engine。 如果问题解决，辛苦反馈下
> > 
> > 
> > <img alt="image" width="1145" src="https://private-user-images.githubusercontent.com/44892851/345867647-164c1560-69f8-493e-a0e3-9799f9a0183d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxMDM3NDUsIm5iZiI6MTcyMDEwMzQ0NSwicGF0aCI6Ii80NDg5Mjg1MS8zNDU4Njc2NDctMTY0YzE1NjAtNjlmOC00OTNlLWEwZTMtOTc5OWY5YTAxODNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA0VDE0MzA0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZkNjRjOGViNDRmYjA0MGFmZjU0MzEyNDgyNjk2ZWUzZmNjYzU2MjhhNTAyNDc5NDhmMzA1Zjk1YzUyNGJiNjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fX7VbB36eLSDANqJdRVjtznYsvjEc6qqI7LF0FodPyU"> 设置了，貌似还不行啊
> 
> @mahaonanStart 需要去Meilisearch中删除掉halo的元数据。

可以，发现是我容器内访问宿主机局域网的7700端口不通。。。奇怪了，之前输入内网ip还是可以的，换成公网能行了。。

**Comment by Rainsheep** [comment]
> > > > @mahaonanStart 看最新的 readme，在设置中需要选择 meilisearch search engine。 如果问题解决，辛苦反馈下
> > > 
> > > 
> > > <img alt="image" width="1145" src="https://private-user-images.githubusercontent.com/44892851/345867647-164c1560-69f8-493e-a0e3-9799f9a0183d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxMDM3NDUsIm5iZiI6MTcyMDEwMzQ0NSwicGF0aCI6Ii80NDg5Mjg1MS8zNDU4Njc2NDctMTY0YzE1NjAtNjlmOC00OTNlLWEwZTMtOTc5OWY5YTAxODNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA0VDE0MzA0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZkNjRjOGViNDRmYjA0MGFmZjU0MzEyNDgyNjk2ZWUzZmNjYzU2MjhhNTAyNDc5NDhmMzA1Zjk1YzUyNGJiNjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fX7VbB36eLSDANqJdRVjtznYsvjEc6qqI7LF0FodPyU"> 设置了，貌似还不行啊
> > 
> > 
> > @mahaonanStart 需要去Meilisearch中删除掉halo的元数据。
> 
> 可以，发现是我容器内访问宿主机局域网的7700端口不通。。。奇怪了，之前输入内网ip还是可以的，换成公网能行了。。

可以参考 readme，两个 docker 放到同一个 networks，可以直接使用 container_name 当域名。

**Comment by Rainsheep** [comment]
插件有什么需要提升的地方吗？   大家可以另起 issue 反馈，有时间我会更新插件。
需要手动选择扩展点这个，就不改了，遵从 halo 官方的机制。
